"""One snapshot supplies the Markdown tables, SVG fallbacks and browser payload."""

import csv
from decimal import Decimal
from datetime import date, timedelta
from html import escape
from io import StringIO
import json
from pathlib import Path

from macro_catalog import SERIES, TOPICS, topic_series

ROOT = Path(__file__).resolve().parents[1]
COLORS = ["#3675b5", "#268566", "#ab6540", "#8064a2", "#c09028", "#3a858a"]


def load_topic(slug, root=ROOT):
    with (root / f"data/macro/{slug}.csv").open(encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    meta = json.loads((root / f"data/macro/{slug}.metadata.json").read_text(encoding="utf-8"))
    return rows, meta


def periods_between(start, end, frequency):
    if frequency == "A":
        return [str(year) for year in range(int(start), int(end)+1)]
    if frequency == "D":
        first, last = date.fromisoformat(start), date.fromisoformat(end)
        return [(first + timedelta(days=i)).isoformat() for i in range((last-first).days+1)]
    per_year = 12 if frequency == "M" else 4
    def ordinal(period):
        return int(period[:4]) * per_year + int(period[-2:] if frequency == "M" else period[-1]) - 1
    return [f"{i//per_year}-{i%per_year+1:02d}" if frequency == "M" else f"{i//per_year}-Q{i%per_year+1}"
            for i in range(ordinal(start), ordinal(end)+1)]


def payload(slug, rows, meta):
    charts = []
    for chart in TOPICS[slug]["charts"]:
        selected = [r for r in rows if r["series_id"] in chart["series"]]
        present = sorted({r["period"] for r in selected})
        frequency = SERIES[chart["series"][0]]["frequency"]
        if chart.get("common_start"):
            start = max(min(r["period"] for r in selected if r["series_id"] == k) for k in chart["series"])
            present = [p for p in present if p >= start]
        periods = periods_between(present[0], present[-1], frequency)
        charts.append(dict(chart, periods=periods, frequency=frequency,
                           unit=SERIES[chart["series"][0]]["unit"],
                           values={k: {r["period"]: float(r["value"]) for r in selected if r["series_id"] == k} for k in chart["series"]}))
        if chart.get("kind") == "stacked":
            values = {(r["series_id"], r["period"]): Decimal(r["value"]) for r in selected}
            charts[-1]["totals"] = {p: float(sum(values[k, p] for k in chart["series"]))
                                    for p in periods if all((k, p) in values for k in chart["series"])}
    return dict(charts=charts, metadata=meta, definitions={k: SERIES[k] for k in topic_series(TOPICS[slug])})


def display(value):
    return "缺失" if value is None else f"{value:,.8f}".rstrip("0").rstrip(".")


def source_notes(meta):
    """Keep historical scope warnings visible after a smaller daily refresh."""
    notes = []
    def visit(detail):
        for name in ("coverage", "coverage_note", "coverage_limit"):
            if detail.get(name):
                notes.append(detail[name].rstrip("。"))
        notes.extend(detail.get("definition_notes", []))
        notes.extend(f"{b['period']}：{b['note']}" for b in detail.get("structural_breaks", []))
        for extra in detail.get("supplemental_sources", []):
            visit(extra)
    for section in ("history", "acquisition"):
        for key in sorted(meta.get(section, {})):
            visit(meta[section][key])
    return list(dict.fromkeys(notes))


def document(slug, rows, meta):
    topic = TOPICS[slug]
    lines = ["<!-- Generated by scripts/sync_macro.py; edit macro_catalog.py/macro_render.py. -->", f"# {topic['title']}：真实数据", "", topic["question"], "", topic["intro"], "",
             f"本页快照获取时间：**{meta['retrieved_at']}**。这是获取时间，不是所有数据的发布日期。每日检查上游；最新统计期以每个指标为准。", "",
             f"[CSV 下载](https://raw.githubusercontent.com/calcky/finance/main/data/macro/{slug}.csv) · "
             f"[来源与采集参数](https://github.com/calcky/finance/blob/main/data/macro/{slug}.metadata.json) · "
             "[最近同步状态](https://github.com/calcky/finance/actions/workflows/update-gdp.yml)", "",
             "```{only} html", f"本站同版快照：{{download}}`CSV <../../data/macro/{slug}.csv>` · {{download}}`元数据 <../../data/macro/{slug}.metadata.json>`", "```", "",
             "网页支持悬停查看、点击固定读数、按期间选择、缩放和定位明细。GitHub、打印或禁用 JavaScript 时显示静态图；数值与网页使用同一快照。", "",
             "## 最新观测与覆盖", "", "| 指标 | 最新期间 | 数值 | 单位 | 本项目起点 | 观测数 | 来源 |", "|---|---|---:|---|---|---:|---|"]
    for key in topic_series(topic):
        selected = sorted([r for r in rows if r["series_id"] == key], key=lambda r: r["period"])
        last = selected[-1]
        source = last["source_url"]
        if "stream/esData" in source:
            page = {"A": "yearData", "Q": "quarterData", "M": "monthData"}[SERIES[key]["frequency"]]
            source = f"https://data.stats.gov.cn/dg/website/page.html#/pc/national/{page}"
            if "shanghai" in key:
                source = "https://data.stats.gov.cn/"
        lines.append(f"| {SERIES[key]['label']} | {last['period']} | {display(float(last['value']))} | {last['unit']} | {selected[0]['period']} | {len(selected)} | [{SERIES[key]['source']}]({source}) |")
    lines += ["", "起点表示本项目当前覆盖范围，不代表该指标从此时才开始发布。旧定义序列的最后一期也不代表来源停止更新。各来源可能存在发布或入库滞后；空白不补零、不插值。发布日期未知的观测在 CSV 中留空。", "",
              "图表的“全部”与 CSV 保留完整已采集历史；缩放近期不会删除早期数据。[历史来源、口径断点与剩余缺口](history-coverage.md)说明回溯范围。", ""]
    for chart in payload(slug, rows, meta)["charts"]:
        compact = chart.get("compact_history", False)
        net_header = '<th>净合计</th>' if chart.get("kind") == "stacked" else ''
        lines += [f"## {chart['title']}", "", chart["explanation"], "",
                  f"![{chart['title']}，单位：{chart['unit']}；完整数值见下方明细](../images/data/macro-{chart['id']}.svg)", "",
                  (f'<details class="macro-details" id="details-{chart["id"]}">' if compact else '<details class="macro-details">'), f"<summary>{escape(chart['title'])}：{'分页数据表' if compact else '展开完整数据表'}（{escape(chart['unit'])}）</summary>",
                  '<div class="macro-table-wrap"><table><thead><tr><th>期间</th>' + ''.join(f"<th>{escape(SERIES[k]['label'])}</th>" for k in chart["series"]) + net_header + '</tr></thead><tbody>']
        for period in reversed(chart["periods"][-60:] if compact else chart["periods"]):
            net_cell = f'<td>{display(chart["totals"].get(period))}</td>' if net_header else ''
            lines.append(f'<tr id="macro-{chart["id"]}-{period}" tabindex="-1"><td>{period}</td>' + ''.join(f'<td>{display(chart["values"][k].get(period))}</td>' for k in chart["series"]) + net_cell + '</tr>')
        lines += ["</tbody></table></div></details>", ""]
        if compact:
            lines += ["明细默认显示最近60期；启用交互后可按期间定位或翻页读取全部历史。禁用JavaScript时，可下载页首完整CSV。", ""]
    for key in topic.get("extra", []):
        lines += [f"## {SERIES[key]['label']}：补充明细", "", SERIES[key]["basis"], "",
                  '<details class="macro-details">', f"<summary>展开完整数据表（{SERIES[key]['unit']}）</summary>",
                  '<div class="macro-table-wrap"><table><thead><tr><th>期间</th><th>数值</th></tr></thead><tbody>']
        for row in sorted((r for r in rows if r["series_id"] == key), key=lambda r: r["period"], reverse=True):
            lines.append(f"<tr><td>{row['period']}</td><td>{display(float(row['value']))}</td></tr>")
        lines += ["</tbody></table></div></details>", ""]
    if meta.get("reported_balance_differences"):
        differences = meta["reported_balance_differences"]
        lines += ["## 原始差额与进出口相减不完全一致", "",
                  f"有 {len(differences)} 个月，官方单列贸易差额与同源进出口金额相减的差异超出显示精度。已核对原始指标、月份和单位；保留官方原值，不静默改算。来源未逐项解释原因，不能仅当作四舍五入或断言为历史修订。单位：亿美元。", "",
                  '<details class="macro-details"><summary>展开差异核对表</summary>',
                  '<div class="macro-table-wrap"><table><thead><tr><th>期间</th><th>出口−进口</th><th>官方差额</th><th>前者−后者</th></tr></thead><tbody>']
        for item in differences:
            lines.append(f"<tr><td>{item['period']}</td><td>{display(float(item['calculated_balance']))}</td><td>{display(float(item['reported_balance']))}</td><td>{display(float(item['residual']))}</td></tr>")
        lines += ["</tbody></table></div></details>", ""]
    lines += ["## 口径与阅读提醒", "", "| 指标 | 口径 |", "|---|---|"]
    for key in topic_series(topic):
        lines.append(f"| {SERIES[key]['label']} | {SERIES[key]['basis']} |")
    lines += ["", *[f"- {c}。" for c in source_notes(meta)], "",
              "日度图保留日历缺口：节假日、没有操作或上游缺失的日期均无观测，不能仅从空白判断原因。图线在缺失处断开；月度与季度图也不插值。", "",
              "来源可能修订历史值。同步程序对已有期间的消失报错，合法数值修订保存在 Git 历史中；这不是包含所有官方初值的实时数据库。这里只摘录指标事实并注明来源，来源文件和机构条款仍归各发布机构。", "",
              f"继续理解：[相关基础知识](../{topic['reading']}.md) · [如何读宏观数据](../reading-macro-data.md) · [全部数据专题](index.md)", ""]
    return "\n".join(lines)


def render(slug, rows, meta, out, font=None, preview_dir=None):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from render_learning_charts import configure_font
    configure_font(font)
    target = out / "docs/images/data"
    target.mkdir(parents=True, exist_ok=True)
    for chart in payload(slug, rows, meta)["charts"]:
        fig, ax = plt.subplots(figsize=(11, 5.6))
        fig.subplots_adjust(left=.10, right=.96, bottom=.22, top=.78)
        fig.text(.06, .92, chart["title"], fontsize=22)
        fig.text(.06, .85, f"单位：{chart['unit']}  |  期间：{chart['periods'][0]} 至 {chart['periods'][-1]}", fontsize=13)
        stacked = chart.get("kind") == "stacked"
        positive, negative = [0.] * len(chart["periods"]), [0.] * len(chart["periods"])
        for key, color in zip(chart["series"], COLORS):
            values = [chart["values"][key].get(p, float("nan")) for p in chart["periods"]]
            if stacked:
                values = [v if p in chart["totals"] else float("nan") for v, p in zip(values, chart["periods"])]
                bottoms = [positive[i] if v >= 0 else negative[i] for i, v in enumerate(values)]
                ax.bar(range(len(values)), values, bottom=bottoms, color=color, width=.8, label=SERIES[key]["label"])
                for i, value in enumerate(values):
                    if value >= 0:
                        positive[i] += value
                    elif value < 0:
                        negative[i] += value
            else:
                ax.plot(range(len(values)), values, color=color, linewidth=2, marker=None if chart.get("compact_history") and chart["frequency"] == "D" else ".",
                        linestyle="--" if key in chart.get("dashed_series", []) else "-",
                        markersize=3 if chart["frequency"] == "D" else 6, label=SERIES[key]["label"])
        if stacked:
            ax.plot(range(len(chart["periods"])), [chart["totals"].get(p, float("nan")) for p in chart["periods"]],
                    color="#203047", linewidth=1.4, label="净合计")
        if "baseline" in chart:
            ax.axhline(chart["baseline"], color="#8492a6", linestyle="--", linewidth=1)
        # Six readable ticks at most, including both endpoints.
        ticks = sorted({round(i*(len(chart["periods"])-1)/5) for i in range(6)})
        ax.set_xticks(ticks, [chart["periods"][i] for i in ticks], fontsize=11)
        ax.tick_params(axis="y", labelsize=12)
        ax.grid(axis="y", color="#e5eaf0")
        if stacked:
            ax.legend(frameon=False, fontsize=9, loc="upper left", bbox_to_anchor=(0, 1.18), ncol=3)
            ax.set_position([.10, .22, .86, .46])
        else:
            ax.legend(frameon=False, fontsize=11, loc="best")
        source = "、".join(dict.fromkeys(SERIES[k]["source"] for k in chart["series"]))
        fig.text(.06, .08, f"来源：{source}；缺失处断线。快照 {meta['retrieved_at'][:10]}（UTC）", fontsize=10)
        stream = StringIO()
        fig.savefig(stream, format="svg", metadata={"Date": None, "Title": chart["title"]})
        (target / f"macro-{chart['id']}.svg").write_text("\n".join(x.rstrip() for x in stream.getvalue().splitlines()) + "\n", encoding="utf-8")
        if preview_dir:
            preview_dir.mkdir(parents=True, exist_ok=True)
            fig.savefig(preview_dir / f"{chart['id']}.png", dpi=130)
        plt.close(fig)
    page = out / f"docs/data/{slug}.md"
    page.parent.mkdir(parents=True, exist_ok=True)
    page.write_text(document(slug, rows, meta), encoding="utf-8")
