"""One snapshot supplies the Markdown tables, SVG fallbacks and browser payload."""

import csv
from datetime import date, timedelta
from html import escape
from io import StringIO
import json
from pathlib import Path

from macro_catalog import SERIES, TOPICS, topic_series

ROOT = Path(__file__).resolve().parents[1]


def load_topic(slug, root=ROOT):
    with (root / f"data/macro/{slug}.csv").open(encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    meta = json.loads((root / f"data/macro/{slug}.metadata.json").read_text(encoding="utf-8"))
    return rows, meta


def periods_between(start, end, frequency):
    if frequency == "D":
        first, last = date.fromisoformat(start), date.fromisoformat(end)
        return [(first + timedelta(days=i)).isoformat() for i in range((last-first).days+1)]
    per_year = 12 if frequency == "M" else 4
    def ordinal(period):
        return int(period[:4]) * per_year + int(period[-2:] if frequency == "M" else period[-1]) - 1
    return [f"{i//per_year}-{i%per_year+1:02d}" if frequency == "M" else f"{i//per_year}-Q{i%per_year+1}"
            for i in range(ordinal(start), ordinal(end)+1)]


def payload(slug, rows, meta):
    charts = []
    for chart in TOPICS[slug]["charts"]:
        selected = [r for r in rows if r["series_id"] in chart["series"]]
        present = sorted({r["period"] for r in selected})
        frequency = SERIES[chart["series"][0]]["frequency"]
        periods = periods_between(present[0], present[-1], frequency)
        charts.append(dict(chart, periods=periods, frequency=frequency,
                           unit=SERIES[chart["series"][0]]["unit"],
                           values={k: {r["period"]: float(r["value"]) for r in selected if r["series_id"] == k} for k in chart["series"]}))
    return dict(charts=charts, metadata=meta, definitions={k: SERIES[k] for k in topic_series(TOPICS[slug])})


def display(value):
    return "缺失" if value is None else f"{value:,.5f}".rstrip("0").rstrip(".")


def document(slug, rows, meta):
    topic = TOPICS[slug]
    lines = ["<!-- Generated by scripts/sync_macro.py; edit macro_catalog.py/macro_render.py. -->", f"# {topic['title']}：真实数据", "", topic["question"], "", topic["intro"], "",
             f"本页快照获取时间：**{meta['retrieved_at']}**。这是获取时间，不是所有数据的发布日期。每日检查上游；最新统计期以每个指标为准。", "",
             f"[CSV 下载](https://raw.githubusercontent.com/calcky/finance/main/data/macro/{slug}.csv) · "
             f"[来源与采集参数](https://github.com/calcky/finance/blob/main/data/macro/{slug}.metadata.json) · "
             "[最近同步状态](https://github.com/calcky/finance/actions/workflows/update-gdp.yml)", "",
             "```{only} html", f"本站同版快照：{{download}}`CSV <../../data/macro/{slug}.csv>` · {{download}}`元数据 <../../data/macro/{slug}.metadata.json>`", "```", "",
             "网页支持悬停查看、点击固定读数、按期间选择、缩放和定位明细。GitHub、打印或禁用 JavaScript 时显示静态图；数值与网页使用同一快照。", "",
             "## 最新观测与覆盖", "", "| 指标 | 最新期间 | 数值 | 单位 | 本项目起点 | 来源 |", "|---|---|---:|---|---|---|"]
    for key in topic_series(topic):
        selected = sorted([r for r in rows if r["series_id"] == key], key=lambda r: r["period"])
        last = selected[-1]
        source = "https://data.stats.gov.cn/dg/website/page.html#/pc/national/monthData" if "stream/esData" in last["source_url"] else last["source_url"]
        lines.append(f"| {SERIES[key]['label']} | {last['period']} | {display(float(last['value']))} | {last['unit']} | {selected[0]['period']} | [{SERIES[key]['source']}]({source}) |")
    lines += ["", "起点表示本项目当前覆盖范围，不代表该指标从此时才开始发布。各来源可能存在发布或入库滞后；空白不补零、不插值。发布日期未知的观测在 CSV 中留空。", ""]
    for chart in payload(slug, rows, meta)["charts"]:
        lines += [f"## {chart['title']}", "", chart["explanation"], "",
                  f"![{chart['title']}，单位：{chart['unit']}；完整数值见下方明细](../images/data/macro-{chart['id']}.svg)", "",
                  '<details class="macro-details">', f"<summary>{escape(chart['title'])}：展开完整数据表（{escape(chart['unit'])}）</summary>",
                  '<div class="macro-table-wrap"><table><thead><tr><th>期间</th>' + ''.join(f"<th>{escape(SERIES[k]['label'])}</th>" for k in chart["series"]) + '</tr></thead><tbody>']
        for period in reversed(chart["periods"]):
            lines.append(f'<tr id="macro-{chart["id"]}-{period}" tabindex="-1"><td>{period}</td>' + ''.join(f'<td>{display(chart["values"][k].get(period))}</td>' for k in chart["series"]) + '</tr>')
        lines += ["</tbody></table></div></details>", ""]
    lines += ["## 口径与阅读提醒", "", "| 指标 | 口径 |", "|---|---|"]
    for key in topic_series(topic):
        lines.append(f"| {SERIES[key]['label']} | {SERIES[key]['basis']} |")
    coverage = list(dict.fromkeys(m.get("coverage", "") for m in meta["acquisition"].values()))
    lines += ["", *[f"- {c}。" for c in coverage if c], "",
              "日度图保留日历缺口：节假日、没有操作或上游缺失的日期均无观测，不能仅从空白判断原因。图线在缺失处断开；月度与季度图也不插值。", "",
              "来源可能修订历史值。同步程序对已有期间的消失报错，合法数值修订保存在 Git 历史中；这不是包含所有官方初值的实时数据库。这里只摘录指标事实并注明来源，来源文件和机构条款仍归各发布机构。", "",
              f"继续理解：[相关基础知识](../{topic['reading']}.md) · [如何读宏观数据](../reading-macro-data.md) · [全部数据专题](index.md)", ""]
    return "\n".join(lines)


def render(slug, rows, meta, out, font=None, preview_dir=None):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from render_learning_charts import configure_font
    configure_font(font)
    target = out / "docs/images/data"
    target.mkdir(parents=True, exist_ok=True)
    for chart in payload(slug, rows, meta)["charts"]:
        fig, ax = plt.subplots(figsize=(11, 5.6))
        fig.subplots_adjust(left=.10, right=.96, bottom=.22, top=.78)
        fig.text(.06, .92, chart["title"], fontsize=22)
        fig.text(.06, .85, f"单位：{chart['unit']}  |  期间：{chart['periods'][0]} 至 {chart['periods'][-1]}", fontsize=13)
        for key, color in zip(chart["series"], ["#3675b5", "#268566", "#ab6540"]):
            values = [chart["values"][key].get(p, float("nan")) for p in chart["periods"]]
            ax.plot(range(len(values)), values, color=color, linewidth=2, marker=".", markersize=3 if chart["frequency"] == "D" else 6, label=SERIES[key]["label"])
        if "baseline" in chart:
            ax.axhline(chart["baseline"], color="#8492a6", linestyle="--", linewidth=1)
        # Six readable ticks at most, including both endpoints.
        ticks = sorted({round(i*(len(chart["periods"])-1)/5) for i in range(6)})
        ax.set_xticks(ticks, [chart["periods"][i] for i in ticks], fontsize=11)
        ax.tick_params(axis="y", labelsize=12)
        ax.grid(axis="y", color="#e5eaf0")
        ax.legend(frameon=False, fontsize=11, loc="best")
        source = "、".join(dict.fromkeys(SERIES[k]["source"] for k in chart["series"]))
        fig.text(.06, .08, f"来源：{source}；缺失处断线。快照 {meta['retrieved_at'][:10]}（UTC）", fontsize=10)
        stream = StringIO()
        fig.savefig(stream, format="svg", metadata={"Date": None, "Title": chart["title"]})
        (target / f"macro-{chart['id']}.svg").write_text("\n".join(x.rstrip() for x in stream.getvalue().splitlines()) + "\n", encoding="utf-8")
        if preview_dir:
            preview_dir.mkdir(parents=True, exist_ok=True)
            fig.savefig(preview_dir / f"{chart['id']}.png", dpi=130)
        plt.close(fig)
    page = out / f"docs/data/{slug}.md"
    page.parent.mkdir(parents=True, exist_ok=True)
    page.write_text(document(slug, rows, meta), encoding="utf-8")
