"""Run independent GDP/macro updates and expose failures without replacing data."""

import argparse
from datetime import datetime, timezone
from html import escape
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile

from macro_catalog import TOPICS
from macro_render import ROOT

ACTIONS = "https://github.com/calcky/finance/actions/workflows/update-gdp.yml"
TITLES = {"gdp": "GDP 历史数据", **{k: v["title"] for k, v in TOPICS.items()}}


def write_changed(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text(encoding="utf-8") != content:
        path.write_text(content, encoding="utf-8")


def update_status(outcomes, root=ROOT, now=None):
    """Keep unchanged checks in CI logs, not timestamp-only repository commits."""
    now = now or datetime.now(timezone.utc).isoformat(timespec="seconds")
    path = root / "data/update-status.json"
    previous = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}
    records = {}
    for slug in TITLES:
        metadata = root / ("data/gdp.metadata.json" if slug == "gdp" else f"data/macro/{slug}.metadata.json")
        snapshot = json.loads(metadata.read_text(encoding="utf-8"))["retrieved_at"]
        old = previous.get(slug, {})
        result = outcomes.get(slug)
        if result is None:
            records[slug] = old or dict(state="unknown", snapshot_at=snapshot, state_since="", error="")
            continue
        current = dict(state=result["state"], snapshot_at=snapshot, error=result.get("error", ""))
        same = current == {k: v for k, v in old.items() if k != "state_since"}
        records[slug] = dict(current, state_since=old["state_since"] if same else now)
    write_changed(path, json.dumps(records, ensure_ascii=False, indent=2, sort_keys=True) + "\n")
    lines = ["<!-- Generated by scripts/sync_data.py. -->", "# 数据更新状态", "",
             "这里记录各专题最近保存的同步状态，数据内容仍来自通过校验的快照。同步失败不代表历史数据作废，也不代表来源没有发布新数据。", "",
             f"[查看最新运行、实际检查时间和完整日志]({ACTIONS})。定时任务每日北京时间 06:17 触发，实际执行可能延迟；若任务未启动、被取消或未通过后续测试，本页可能尚未反映该次运行。", "",
             "为避免无意义提交，状态和快照不变时不刷新本页时间。“状态变更”包含快照变更，不是最近检查时间；“快照获取”也不是统计期或官方发布日期。表中时间为 UTC，北京时间加 8 小时。每个专题的指标表另列最新统计期。", "",
             "“未记录”表示尚未记录逐专题检查；“失败”时仍展示上次有效快照。", "",
             "| 专题 | 同步状态 | 快照获取 | 状态变更 |", "|---|---|---|---|"]
    labels = {"ok": "通过", "failed": "失败，保留快照", "unknown": "未记录"}
    for slug, title in TITLES.items():
        record = records[slug]
        snapshot = escape(record['snapshot_at']).removesuffix('+00:00').replace('T', '<br>')
        changed = escape(record['state_since']).removesuffix('+00:00').replace('T', '<br>') or '—'
        lines.append(f"| [{title}]({slug}.md) | {labels[record['state']]} | {snapshot} | {changed} |")
    failures = [(slug, r) for slug, r in records.items() if r["state"] == "failed"]
    if failures:
        lines += ["", "## 未解决的同步失败", ""]
        for slug, record in failures:
            # Source errors are literal text, never executable HTML or Markdown.
            lines += [f"### {TITLES[slug]}", "", f"<pre>{escape(record['error'])}</pre>", ""]
    lines += ["", "各专题独立更新；同一专题必须完成全部来源与数据校验后才替换 CSV、元数据和图表。共享来源失败时，依赖它的多个专题都会保留原快照。部分成功不会让整次运行显示成功。", ""]
    write_changed(root / "docs/data/update-status.md", "\n".join(lines))
    return records


def run(command, log_path):
    """Stream logs while retaining the complete attempt as a CI artifact."""
    with log_path.open("w", encoding="utf-8") as log:
        with subprocess.Popen(command, cwd=ROOT, stdout=subprocess.PIPE,
                              stderr=subprocess.STDOUT, text=True, encoding="utf-8") as process:
            for line in process.stdout:
                print(line, end="", flush=True)
                log.write(line)
            return process.wait()


def attempt(directory, backfill):
    directory.mkdir(parents=True, exist_ok=True)
    outcomes = {}
    gdp_log = directory / "gdp.log"
    code = run([sys.executable, "-u", str(ROOT / "scripts/sync_gdp.py")], gdp_log)
    outcomes["gdp"] = dict(state="ok") if code == 0 else dict(
        state="failed", error="\n".join(gdp_log.read_text(encoding="utf-8").splitlines()[-6:]))
    macro_report = directory / "macro.json"
    # The report belongs to this attempt, even when a caller reuses a log directory.
    macro_report.write_text("{}\n", encoding="utf-8")
    command = [sys.executable, "-u", str(ROOT / "scripts/sync_macro.py"),
               "--keep-going", "--report", str(macro_report)]
    if backfill:
        command.append("--backfill")
    macro_log = directory / "macro.log"
    code = run(command, macro_log)
    reported = json.loads(macro_report.read_text(encoding="utf-8"))
    for slug in TOPICS:
        outcomes[slug] = reported.get(slug, dict(state="failed", error=(
            f"Macro update exited {code} without a topic result: " +
            "\n".join(macro_log.read_text(encoding="utf-8").splitlines()[-6:]))))
    # Any unreported global failure must not be disguised as a successful attempt.
    failed = code != 0 or any(r["state"] == "failed" for r in outcomes.values())
    report = dict(checked_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
                  outcomes=outcomes, failed=failed)
    (directory / "attempt.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    update_status(outcomes)
    summary = ["## 数据同步结果", "", "| 专题 | 结果 |", "|---|---|"]
    summary.extend(f"| {TITLES[k]} | {'通过' if v['state'] == 'ok' else '失败，保留原快照'} |" for k, v in outcomes.items())
    for slug, result in outcomes.items():
        if result["state"] == "failed":
            detail = result["error"].replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")
            print(f"::error title={slug} sync failed::{detail}", flush=True)
    if os.environ.get("GITHUB_STEP_SUMMARY"):
        with open(os.environ["GITHUB_STEP_SUMMARY"], "a", encoding="utf-8") as stream:
            stream.write("\n".join(summary) + "\n")
    return int(failed)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--backfill", action="store_true")
    parser.add_argument("--report-dir", type=Path)
    parser.add_argument("--render-status", action="store_true", help="Render saved status without claiming a new check")
    args = parser.parse_args()
    if args.render_status:
        update_status({})
        return 0
    if args.report_dir:
        return attempt(args.report_dir.resolve(), args.backfill)
    with tempfile.TemporaryDirectory(prefix="finance-sync-") as temporary:
        return attempt(Path(temporary), args.backfill)


if __name__ == "__main__":
    raise SystemExit(main())
